#use_frameworks!
platform :ios, '9.0'

target 'White-SDK-iOS_Example' do
  pod 'White-SDK-iOS', :path => '../'
  pod 'Masonry'
  target 'White-SDK-iOS_Tests' do
    inherit! :search_paths

    
  end
end
