#!/bin/bash
BASEDIR=$(cd $(dirname "$0"); pwd -P)
set -exo pipefail

cd $BASEDIR

cp ../white-sdk-iOS/WhiteSDK/Classes/*/*.h ./White-SDK-iOS/Headers
cp ../white-sdk-iOS/WhiteSDK/Classes/*.h ./White-SDK-iOS/Headers
