#!/bin/bash
BASEDIR=$(cd $(dirname "$0"); pwd -P)
set -exo pipefail

cd $BASEDIR

cp ../white-sdk/native-sdk-render/build/index.html ./White-SDK-iOS/Resource/index.html
cp ../white-sdk/native-sdk-render/build/static/js/*.js ./White-SDK-iOS/Resource/static/js
cp ../white-sdk/native-sdk-render/build/static/js/*.js.map ./White-SDK-iOS/Resource/static/js
cp ../white-sdk/native-sdk-render/build/static/css/*.css ./White-SDK-iOS/Resource/static/css
cp ../white-sdk/native-sdk-render/build/static/css/*.css.map ./White-SDK-iOS/Resource/static/css
